### PR TITLE
Load youtube via query

### PR DESCRIPTION
**Pull request by kostasx**
This is a [branch](https://github.com/kostasx/oTranscribe/tree/load-youtube-via-query) for automatically loading a YouTube video based on a query parameter (v=YOUTUBE_ID). The branch also supports opening the video at a specific timeframe using a second query parameter (t=SECONDS or t=HH:MM:SS).

Here are some working online examples:

Automatic loading of a video: [http://kostasx.github.io/oTranscribe/?v=VrMHA3yX_QI](http://kostasx.github.io/oTranscribe/?v=VrMHA3yX_QI)
 
Automatic loading of a video on a specific point in time using seconds notation: [http://kostasx.github.io/oTranscribe/?v=VrMHA3yX_QI&t=506](http://kostasx.github.io/oTranscribe/?v=VrMHA3yX_QI&t=506)

Automatic loading of a video on a specific point in time using HH:MM:SS notation: [http://kostasx.github.io/oTranscribe/?v=VrMHA3yX_QI&t=45:54](http://kostasx.github.io/oTranscribe/?v=VrMHA3yX_QI&t=45:54)

Check it out, and let me know.

### CODE REVIEW

**Comment by ejb** [comment]
I'll take a full look tomorrow, but at first glance this looks like a 💯 pull request. @MikeRidgway, does this fit your needs for DIY Captions Launcher?

**Comment by ejb** [comment]
Seems robust enough to me. Thanks so much @kostasx! If you feel like hacking away some more on oTranscribe, feel free to drop me an email. Or pick another issue on GitHub and go wild! 😄

**Comment by MikeRidgway** [comment]
Thanks, everyone. I'll add this to the DIY Captions Chrome Extension
presently.

**Comment by MikeRidgway** [comment]
oTranscribe has now been added as a launch option in the "DIY Captions"
Launcher Chrome extension.
Here's the link to the installation page:
https://chrome.google.com/webstore/detail/diy-captions-launcher-for/nfmohppoonnamhhboojkgffnjmbekckl
To use it, simply go to any YouTube video page and then click "Open video
for transcription in oTranscribe" in the extensions pop-up menu.

**Pull request merged**
