### PR TITLE
Added the Romanian localization

### PR DESCRIPTION
**Pull request by ibriq**
Hey, so here is the Romanian localisation file that I am using for a personal project. I'd be glad if it were to be useful for anyone else.

Cheers,
Iain

### CODE REVIEW

**Comment by ejb** [comment]
Thanks Iain! Would you mind adding [these three additional lines](https://github.com/oTranscribe/oTranscribe/blob/master/src/l10n/english.ini#L55)?

**Comment by ibriq** [comment]
Done!

**Comment by ejb** [comment]
Thanks! Sorry for the wait. I've put a test version up - would you mind checking over for any typos?
https://github.com/oTranscribe/oTranscribe/pull/43

**Comment by ejb** [comment]
Great, that's now on otranscribe.com! Thanks so much for your help, I really appreciate it!

**Pull request merged**
